window.WORD_LIST = [
  "REACH", "RELISH", "LICH", "RICH", "RICE", "RIDER", "RAIL", "RELIC",
  "TEACH", "PEACH", "LEECH", "BLEACH", "BEACH", "EACH", "HATCH",
  "MATCH", "PATCH", "CATCH", "SCRATCH", "WATCH",
  "APPLE", "AMPLE", "MAPLE", "SAMPLE", "TRAMPLE", "EXAMPLE",
  "BRANCH", "CRUNCH", "LUNCH", "BUNCH", "MUNCH",
  "STONE", "STONY", "TONES", "ALONE", "CLONE", "PRONE", "SHONE",
  "FLICK", "TRICK", "BRICK", "STICK", "CLICK", "QUICK"
];