window.WORD_LIST = [
  "REACH", "RELISH", "LICH", "RICH", "RICE", "RIDER", "RAIL", "RELIC",
  "TEACH", "PEACH", "LEECH", "BLEACH", "BEACH", "EACH", "HATCH",
  "MATCH", "PATCH", "CATCH", "SCRATCH", "WATCH",
  "APPLE", "AMPLE", "MAPLE", "SAMPLE", "TRAMPLE", "EXAMPLE",
  "BRANCH", "CRUNCH", "LUNCH", "BUNCH", "MUNCH",
  "STONE", "STONY", "TONES", "ALONE", "CLONE", "PRONE", "SHONE",
  "FLICK", "TRICK", "BRICK", "STICK", "CLICK", "QUICK",
  "FLAME", "FRAME", "CRAME", "BLAME", "SHAME", "GAME", "TAME", "NAME",
  "FROST", "CROSS", "LOSS", "MOSS", "BOSS", "GLOSS", "FLOSS",
  "SPOON", "MOON", "NOON", "BOON", "CROON", "BALLOON",
  "TRAIN", "BRAIN", "DRAIN", "GRAIN", "CHAIN", "PLAIN", "STAIN",
  "WRITE", "BRITE", "RIGHT", "NIGHT", "SIGHT", "LIGHT", "MIGHT",
  "ROUND", "SOUND", "BOUND", "FOUND", "GROUND", "WOUND",
  "CHORD", "WORD", "SWORD", "WORLD", "WHIRL", "TWIRL",
  "PLANT", "CHANT", "GRANT", "SLANT", "BRANT", "GIANT",
  "DREAM", "CREAM", "STREAM", "BEAM", "TEAM", "SCREAM",
  "BREAD", "SPREAD", "DREAD", "THREAD", "TREAD"
];
